### ISSUE TITLE
How to change the highlight color for Brightest

### ISSUE THREAD

**Issue by ayushxx7** [osyo-manga/vim-brightest#17]
It's a great plugin, but it conflicts with my color scheme so I can't easily identify whether a word is highlighted because of syntax highlight or brightest. Hence, is it possible to change the color of the brightest highlight?

**Comment by osyo-manga** [comment]
hi, You can set the highlight group with `g:brightest#highlight`.

```vim
let g:brightest#highlight = {
\	"group" : "Error",
\}
```

**Comment by ayushxx7** [comment]
Can I change the color from red to something else?

**Comment by osyo-manga** [comment]
Yes, set your favorite highlight group.
You can see the highlight group with `:highlight`

**Comment by ayushxx7** [comment]
Okay, thanks! That worked. Scanning `:highlight` right now.
