### ISSUE TITLE
Do not highlight word under cursor

### ISSUE THREAD

**Issue by p0deje** [osyo-manga/vim-brightest#4]
Thanks for a great plugin!

Is it possible to highlight all the matching words but do not highlight word under cursor itself?

**Comment by sergey-vlasov** [comment]
According to docs, this can be done via:

```
let g:brightest#highlight_in_cursorline = {
\ "group" : "BrightestCursorLineBg"
\}
```

but it doesn't work for me. However this works:
```
let g:brightest#highlight_in_cursorline = {
\ "group" : "BrightestUnderline",
\}
```
Looks like a bug.

**Comment by osyo-manga** [comment]
oops.
Thanks for issues.
Is Enabled `underline` in `:highlight`?
Please check `:highlight BrightestUnderline` output.

**Comment by sergey-vlasov** [comment]
```
:highlight BrightestUnderline
BrightestUnderline xxx term=underline cterm=underline gui=underline

:highlight underline
E411: highlight group not found: underline
```

There is no problem with using `BrightestUnderline`.


The problem is that `BrightestCursorLineBg` is being overwritten by `g:brightest#highlight` group.

My `vimrc`:
```vim
let g:brightest#highlight = {
\ "group" : "BrightestReverse",
\}

let g:brightest#highlight_in_cursorline = {
\ "group" : "BrightestCursorLineBg",
\}
```

```
:highlight BrightestCursorLineBg
BrightestCursorLineBg xxx term=reverse cterm=reverse gui=reverse
```

**Comment by osyo-manga** [comment]
`xxx` with underline?

e.g.
![](http://i.gyazo.com/f40db132935a1055efef4a1c546ba32f.png)

**Comment by sergey-vlasov** [comment]
Yes:

![untitled](https://cloud.githubusercontent.com/assets/717109/7045832/3964d220-de0a-11e4-81e5-af65b7b3345f.png)

**Comment by osyo-manga** [comment]
I got what you mean.
`BrightestCursorLineBg` can not be set to `g:brightest#highlight_in_cursorline`.
`BrightestCursorLineBg` is for using with `'cursorline'`.
Please set other `BrightestCursorLineBg`.

**Comment by p0deje** [comment]
Using `BrightestUnderline` makes current word underlined. I still can't figure out if there was not to apply any rules to word under cursor.

**Comment by osyo-manga** [comment]
I added it.
Please update plugin and setting.

```vim
let g:brightest#highlight = {
\ "group" : "BrightestUnderline",
\}


let g:brightest#highlight_in_cursorline = {
\ "group" : "NONE",
\}
```

![](http://i.gyazo.com/55901a2e152ee1bed2ac2c7c58a98f9d.png)

**Comment by p0deje** [comment]
Updated and added your config

```
Error detected while processing function brightest#on_CursorMoved..brightest#highlighting..<SNR>158_highlighting..<SNR>158_single_word..<SNR>158_highlight..<SNR>164_highlight..373..369:
line   11:
E28: No such highlight group name: NONE
```

**Comment by osyo-manga** [comment]
hmmmmmm...
Please update plugin and use `BrightestNONE`.

```vim
let g:brightest#highlight = {
\ "group" : "BrightestUnderline",
\}

let g:brightest#highlight_in_cursorline = {
\ "group" : "BrightestNONE",
\}
```

**Comment by p0deje** [comment]
Thanks, that works perfectly!

**Comment by sergey-vlasov** [comment]
Indeed, works great now!
