### ISSUE TITLE
:BrightestToggle

### ISSUE THREAD

**Issue by mattboehm** [osyo-manga/vim-brightest#7]
Do `:BrightestEnable` if it's disabled, else do `:BrightestDisable`. 

Something like:

    command! -bar BrightestToggle if g:brightest_enable | BrightestDisable | else | BrightestEnable | endif

It's easy enough for me to add it to my .vimrc, but maybe other people will find it useful. I find it useful because it lets me use a single key mapping to turn the plugin off/on.

**Comment by osyo-manga** [comment]
Thanks for issues :)
I added `:BrightestToggle`.

**Comment by mattboehm** [comment]
Thanks!
