### ISSUE TITLE
Avoid clearing highlight on CursorMoved

### ISSUE THREAD

**Issue by sergey-vlasov** [osyo-manga/vim-brightest#8]
When using `let g:brightest#enable_on_CursorHold=1` there is an irritating flickering when moving the cursor, due to the highlighting begin updated every time.

To fix the issue I had to comment `call brightest#hl_clear()` in `brightest#on_CursorMoved()`:

```vim
function! brightest#on_CursorMoved()
"	if s:is_enable_on_cursorhold()
"		call brightest#hl_clear()
"	endif
	if s:is_enable() && !s:is_enable_on_cursorhold()
		call brightest#highlighting()
	endif
endfunction
```

**Comment by osyo-manga** [comment]
hmm...I added `g:brightest#enable_clear_highlight_on_CursorMoved` option.
Plase set `let g:brightest#enable_clear_highlight_on_CursorMoved = 0`.

**Comment by sergey-vlasov** [comment]
Works great, thanks!
